services:
  inpsyght:
    container_name: inpsyght
    build:
      context: ./inpsyght-backend
      dockerfile: Dockerfile
    image: inpsyght:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: inpsyghtDB
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
      DATABASE_SSL: ${DATABASE_SSL}
    volumes:
      - ./inpsyght-backend/config:/opt/app/config
      - ./inpsyght-backend/src:/opt/app/src
      - ./inpsyght-backend/package.json:/opt/inpsyght-backend/package.json
      - ./inpsyght-backend/package-lock.json:/opt/inpsyght-backend/package-lock.json

      - .env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - '1337:1337'
    networks:
      - inpsyght
    depends_on:
      - inpsyghtDB
      
  inpsyghtDB:
    container_name: inpsyghtDB
    build:
      context: ./inpsyght-backend
      dockerfile: Dockerfile
    platform: linux/amd64 
    restart: unless-stopped
    env_file: .env
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - inpsyght-data:/var/lib/postgresql/data/ #using a volume
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder

    ports:
      - '5432:5432'
    networks:
      - inpsyght
      
  inpsyghtAdminer:
    container_name: inpsyghtAdminer
    build:
      context: ./inpsyght-backend
      dockerfile: Dockerfile
    env_file: .env
    image: adminer
    restart: unless-stopped
    ports:
      - '9090:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=inpsyghtDB
    networks:
      - inpsyght
    depends_on:
      - inpsyghtDB

volumes:
  inpsyght-data:

networks:
  inpsyght:
    name: Inpsyght
    driver: bridge
